---
kind: pipeline
name: admin-merchant-dev

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  settings:
    restore: true
    cache_key: [DRONE_REPO_OWNER, DRONE_REPO_NAME]
    mount:
    - ./node_modules
  volumes:
   - name: cache
     path: /cache

- name: build-dev
  image: node:10.15.3
  commands:
  - rm -rf .npmrc
  - yarn --ignore-optional && npm run build:dev

- name: rebuild-cache
  image: drillster/drone-volume-cache
  settings:
    rebuild: true
    cache_key: [DRONE_REPO_OWNER, DRONE_REPO_NAME]
    mount:
    - ./node_modules
  volumes:
   - name: cache
     path: /cache

- name: deploy-dev
  image: drillster/drone-rsync
  settings:
    user: root
    hosts: [dev.shiqun.api.iyov.io,dev.admin.merchant.jianbolive.com]
    source: ./dist/*
    target: /home/wwwroot/admin_merchant
    include: []
    exclude: []
    key:
      from_secret: ssh_key
    script:
      - sudo chmod 755 -R /home/wwwroot/admin_merchant

volumes:
  - name: cache
    host:
      path: /tmp

trigger:
  branch:
  - dev

---
kind: pipeline
name: admin-merchant-prod

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  settings:
    restore: true
    cache_key: [DRONE_REPO_OWNER, DRONE_REPO_NAME]
    mount:
    - ./node_modules
  volumes:
   - name: cache
     path: /cache

- name: build-prod
  image: node:10.15.3
  commands:
  - yarn --ignore-optional && npm run build

- name: rebuild-cache
  image: drillster/drone-volume-cache
  settings:
    rebuild: true
    cache_key: [DRONE_REPO_OWNER, DRONE_REPO_NAME]
    mount:
    - ./node_modules
  volumes:
   - name: cache
     path: /cache

- name: deploy-prod
  image: drillster/drone-rsync
  settings:
    user: root
    hosts: [shiqun.api.iyov.io,admin.merchant.jianbolive.com]
    source: ./dist/*
    target: /home/www/admin_merchant
    include: []
    exclude: []
    key:
      from_secret: ssh_key
    script:
      - sudo chmod 755 -R /home/www/admin_merchant

volumes:
  - name: cache
    host:
      path: /tmp

trigger:
  branch:
  - master
