---
kind: pipeline
name: admin-merchant-dev

steps:
- name: build-dev
  image: node:10.15.3
  commands:
  - npm install
  - npm run build:dev

- name: deploy-dev
  image: drillster/drone-rsync
  settings:
    user: root
    hosts: [39.96.218.194]
    source: ./dist/*
    target: /home/wwwroot/admin_merchant
    include: []
    exclude: []
    key:
      from_secret: ssh_key

trigger:
  branch:
  - dev

---
kind: pipeline
name: admin-merchant-prod

steps:
- name: build-prod
  image: node:10.15.3
  commands:
  - npm install
  - npm run build

- name: deploy-prod
  image: drillster/drone-rsync
  settings:
    user: root
    hosts: [shiqun.api.iyov.io]
    source: ./dist/*
    target: /home/wwwroot/admin_merchant
    include: []
    exclude: []
    key:
      from_secret: ssh_key

trigger:
  branch:
  - master

---
kind: pipeline
name: after-notify

notify:
  email:
    from: coding@imicha.com
    host:
      from_secret: email_host
    username:
      from_secret: email_username
    password:
      from_secret: email_password
    recipients: [siyuanh@imicha.com, xingchaof@imicha.com, hailinh@imicha.com]
